-- Quarantine: held pending a decision.
--
-- Distinct from OUT_OF_SERVICE because the two end differently. Out-of-service
-- ends when the unit is repaired and returned; quarantine ends when somebody
-- decides, and one of the decisions is "retire it". Sharing a status would put
-- held gear in the Out of Service list beside a standing "Return to service"
-- button — a safety hold cleared in one click by somebody with no idea it was
-- a hold.
--
-- Appended to the enum rather than inserted: Postgres orders enum values by
-- definition, and adding mid-list rewrites the type.
ALTER TYPE "AssetStatus" ADD VALUE 'QUARANTINED';
